name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: list files
      run: ls

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rutujkc/wisecow-aap-1:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure kubeconfig
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
        cat $HOME/.kube/config

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Debug kubeconfig
      run: |
           echo "Kubeconfig content:"
           cat $HOME/.kube/config
           echo "Context details:"
           kubectl config get-contexts
           echo "Cluster info:"
           kubectl cluster-info


    - name: Validate kubectl configuration
      run: |
           kubectl version --client
    
    - name: Deploy to Kubernetes
      run: |
        kubectl create -f kubernetes/app-deployment.yaml --validate=false
        kubectl create -f kubernetes/app-service.yaml --validate=false
        kubectl create -f kubernetes/app-ingress.yaml --validate=false
